<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bskton\Example
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Example API client
 *
 * Provide a client for Example API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bskton\Example;

use \Bskton\Example\Configuration;
use \Bskton\Example\ApiException;
use \Bskton\Example\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bskton\Example
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getComments
     *
     * .
     *
     */
    public function testGetComments()
    {
    }

    /**
     * Test case for postComment
     *
     * .
     *
     */
    public function testPostComment()
    {
    }

    /**
     * Test case for updateComment
     *
     * .
     *
     */
    public function testUpdateComment()
    {
    }
}
